### ISSUE TITLE
Generally very slow and laggy

### ISSUE THREAD

**Issue by steven-fernandez** [driftyco/ionic-creator-issues#265]
Generally very slow and laggy. I've tried it a few times but wasn't a nice experience.

**Comment by daveyjones** [comment]
This may have to do with the constant auto saving...not sure. I've found that if I reload the page every other minute I can usually make some progress.

**Comment by steven-fernandez** [comment]
I could take a look. I have a lot of experience in similar applications. For me it needs to be smooth and fast. Also a bit more user friendly. Just an opinion.

**Comment by mareczek** [comment]
this might have something to do with a endless loop of NaN (take a look at the attachment
<img width="1672" alt="screen shot 2015-09-28 at 12 47 52" src="https://cloud.githubusercontent.com/assets/791743/10133719/d9478ad2-65df-11e5-8444-2bdb0b1469b1.png">
)

**Comment by mareczek** [comment]
This also prevents me from adding any elements to the content of a tab

**Comment by matthewkremer** [comment]
We just pushed a MAJOR release on Tuesday that is much better, bug free, and easy to use. Please check it out and let me know what you think before I close this :)

**Comment by cesarlugosis** [comment]
The latest release is much better, and faster, but still gets laggy after a few minutes. Reopening the app helps with that. A lot of bugs fixed but I still find some ... I added buttons within a couple item-list inside a list , then I added buttons outside the list, try to select one of them by clicking on it and it selects the other button within the list instead. Also tried selecting the button from the menu list in the upper left section and same think happens, it selects the wrong button instead.

Another issue is that in the previous version I included a card within a list-item and a button within the card. Now on this version I tried to do the same and it doesn't let me drag a button inside a card within a list-item, it places the button outside the list when I try that. There was significant improvement, now when I export my app and use it as a template it creates an app that looks just the way it looked on Creator, you are getting much closer, I will look forward for your progress I think it will be a great fast prototyping tool ! I wish you could create a sliding menu page, similar to the one you have on your Ionic templates, I really need that one.

**Comment by birbilis** [comment]
maybe one should also report what browser they're using. I was trying on older machine with Edge and Firefox on Win10 and was quite slow. I'm now trying on Chrome at a faster Win10 machine and goes fine

**Comment by matthewkremer** [comment]
Hey @cesarlugosis,

Think you could open up new issues for what you are experiencing?

Thanks,
Matt

**Comment by Narayon** [comment]
I'm using Win10 with Chrome, on a Intel i7 ivy bridge (with hyper-threading). The Chrome task manager shows the page using 13% of my cpu capabilities. There's a major performance problem and it shows on the very laggy interface.
